##  load library --------------------
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(stringr)
library(shinyjs)
library(plotly)
library(shinythemes)
library(shinyWidgets)
library(htmltools)
library(htmlwidgets)
library(shinymaterial)
library(randomForest)
library(ranger)
library(forcats)
library(shinycssloaders)
library(readxl)
library(leaflet)
library(RColorBrewer)
library(RSQLite)
library(sf)


#setwd("C:/Users/User/Desktop/Hackathon")
setwd("G:/Meine Ablage/Data_solutions/Traffic accidents/shiny")

#dataset_clean <- readRDS("dataset_clean.rds")
#data_c <- readRDS("data_c.rds")
merged_data_sf <- readRDS("merged_data_sf.rds")
merged_data_sf_p <- readRDS("merged_data_sf_p.rds")
merged_data_sf_t <- readRDS("merged_data_sf_t.rds")
